### ISSUE TITLE
Plugin causes hyprland crash after aquamarine merge

### ISSUE THREAD

**Issue by leon-erd** [VirtCode/hypr-dynamic-cursors#12]
See https://github.com/hyprwm/Hyprland/issues/6943 :)

**Comment by VirtCode** [comment]
just pushed a commit, which *could* fix this crash, or it could cause one at least

could you try that and see whether that was the issue?

**Comment by leon-erd** [comment]
Yes that seems to fix it! Thanks for the fast response :)
