### ISSUE TITLE
Cursor artifacts/ghosting

### ISSUE THREAD

**Issue by leon-erd** [VirtCode/hypr-dynamic-cursors#13]
After reboot I'm experiencing cursor artifacts/ghosting.
Interestingly as soon as I start recording (with `wl-screenrec`) the artifacts go away and are not coming back even after I finish the recording.

https://github.com/user-attachments/assets/0e0c8c37-0a57-4017-a928-3676fd9cc1a5

**Comment by VirtCode** [comment]
these look like software cursor damage issues... do you use software cursors?

also, can you set `opengl:force_introspection = true` (or float a transparent window (with non-xray blur)) and see whether the artifacts disappear?

**Comment by leon-erd** [comment]
How can I check if software cursors are used?
I have at least not disabled hardware cursors: `cursor:no_hardware_cursors = false`.
Artifacts are still there after setting `opengl:force_introspection = true`

**Comment by VirtCode** [comment]
okay, very interesting

try enabling `plugin:dynamic-cursors:hw_debug = true` and see whether there's a colorful background around the cusor, if so - you are using hardware cursors, otherwise software cursors

**Comment by leon-erd** [comment]
Thanks! Turns out Im using hardware cursors :)

**Comment by leon-erd** [comment]
I think artifacts only occur on external monitors :thinking:

**Comment by leon-erd** [comment]
https://github.com/user-attachments/assets/2f2188f2-ba13-422c-9229-dc20825aaf33

**Comment by VirtCode** [comment]
this is really weird, it looks like software cursors sometimes seem to be enabled just for a frame or two

I've pushed some verbose logs to a new branch [aq-artifacts](https://github.com/VirtCode/hypr-dynamic-cursors/tree/aq-artifacts) (can also send you a patch, but heard branches are easier to deal with on nix?). 

Can you try building from this one and send the logs (warning, they will be spammed quite a bit).

**Comment by leon-erd** [comment]
How do I obtain the logs?
Is it just regular hyprland logs under `$XDG_RUNTIME_DIR/hypr`?
I have `debug:disable_logs = false`

**Comment by leon-erd** [comment]
Also the artifacts were not introduced by the aq merge. I noticed them before that as well

**Comment by leon-erd** [comment]
Yea looks like its rendering software cursors :thinking: 
[hyprland.log](https://github.com/user-attachments/files/16326139/hyprland.log)

**Comment by VirtCode** [comment]
Thanks for the logs, that's perfect.

Weird that it indeed does seem to switch to sw cursors now and then, and interresting that it also happened before aq. I assume the artifacts only appear with this plugin loaded right?

I've pushed some more logs to the branch, which will print *why* sw cursors are used. Can you try this when you find time? You could also enable trace logging by starting hyprland with the envs `HYPRLAND_TRACE=1` and `AQ_TRACE=1`, so we get some more info.

**Comment by leon-erd** [comment]
Yea artifacts only happen with this plugin loaded.
Looks like a lot of hw failures :sweat_smile: 
The log file with `HYPRLAND_TRACE=1` and `AQ_TRACE=1` is quite big so I had to compress it

[hyprland.log](https://github.com/user-attachments/files/16337040/hyprland.log)

[hyprland_trace.tar.gz](https://github.com/user-attachments/files/16337048/hyprland_trace.tar.gz)

**Comment by VirtCode** [comment]
well, the hardware failures only occur at the beginning, that's probably normal

however, for some reason, the software locks (counter how many occasions force the use of software cursors) are negative
```
[LOG] [dynamic-cursors] current sw cursor status: hw failure = false, locks = -1
```

which fails a check whether they are `0`. I can quickly patch this by doing `<=` check instead, but I wonder where the lock is decreased incorrectly. From looking at my plugin, it doesn't *seem* to happen here, also doesn't seem to happen on hyprland itself. Do you have any other plugins loaded?

**Comment by leon-erd** [comment]
Hyprexpo

**Comment by leon-erd** [comment]
Ahh very nice catch! It actually only occurs when hyprexpo is enabled.
Hyprexpo has to be enabled from the start though. 
If I boot into Hyprland with hyprexpo disabled and then enable hyprexpo there are no artifacts.
However, when booting into Hyprock with hyprexpo enabled there are artifacts and they remain even after disabling hyprexpo.
Is this something that can be fixed in this repo or should I submit an issue to hyprexpo?

**Comment by VirtCode** [comment]
No I wouldn't submit an issue to hyprexpo, because I don't actually think they are locking/unlocking sw cursors from what I can judge by looking through the source. Very weird.

I'll push a fix here, and we can investigate afterwards if you want to.

**Comment by leon-erd** [comment]
Sure!

**Comment by VirtCode** [comment]
can you quickly build from main again (probably requires latest hyprland rev), and check whether that actually worked?

**Comment by leon-erd** [comment]
Haha looks dirty but works like a charm :D

**Comment by leon-erd** [comment]
Can you maybe rebase the inverted branch to include the commits from main?
I would like to try that out :)

**Comment by VirtCode** [comment]
> Haha looks dirty but works like a charm :D

Yeah, it is dirty, but if it works it works ^^. I looked some more through the hyprland code and the only scenario I can imagine, where the counter is set below zero, is when software cursors are *locked* when only one monitor is connected, and *unlocked* after an additional output has been connected. But then the question is why it was locked in the first place. I think I'll not further investigate that, probably the easiest is to clamp to zero on hyprland itself one day (already does that when only locking *one* monitor, not all). 

Anyways, thank you so much for your help and patience haha. 

> Can you maybe rebase the inverted branch to include the commits from main?

I can have a look at that later this evening if it is not too much work.

Be warned though that I don't really plan to maintain this branch (or merge it), because it would introduce a lot more complexity into the currently relatively simple plugin, and would substantially increase the maintenance burden. I implemented it some time ago because I had some spare time on my hands was curious about how it would be done. I might consider having it as a separate plugin in the future (with other, more interesting effects, like cursor trails), but I currently don't have the time for that.

**Comment by VirtCode** [comment]
Okay, did such a horrendous job with rebasing, so I pushed it to a separate branch [inverted-aq](https://github.com/VirtCode/hypr-dynamic-cursors/tree/inverted-aq). Getting stuff proper and cleaned up would require quite a bit of time which I don't have right now. Anyway, the inverted cursors work now again on aq, but only when software cursors are enabled. So the following should do the trick:

```
cursor:no_hardware_cursors = true

# required, otherwise inversion won't have a buffer to go off of
opengl:force_introspection = true
```

See the readme on that other branch on how to configure stuff, most things should still work. I hope this is enough to test for a bit, but as I mentioned I don't really intend on maintaining it currently, so this will have to do for now.

**Comment by leon-erd** [comment]
Thanks a lot for all you help and for fixing this so fast! I only did some testing :upside_down_face: 
And also thanks for your rebasing work haha. Its nice to play around with this a bit but yea its probably a good idea to not add its complexity to main :)
