### ISSUE TITLE
Cursor's swapchain is handled incorrectly

### ISSUE THREAD

**Issue by vaxerski** [VirtCode/hypr-dynamic-cursors#14]
Results in the cursor jumping around on image change.

You'll want to apply this patch from hl
https://github.com/hyprwm/Hyprland/commit/4c3b03516209a49244a8f044143c1162752b8a7a

Cheers.

**Comment by VirtCode** [comment]
commited, thanks a lot for the heads up!

**Comment by vaxerski** [comment]
it would drive me crazy so I decided to fix it. Once you notice it, it becomes annoying
