### ISSUE TITLE
Change mention of wlroots to Aquamarine or whatever is responible for drawing cursors now

### ISSUE THREAD

**Issue by nonetrix** [VirtCode/hypr-dynamic-cursors#15]
Inside of the README you have the following line
```
hardware cursor rendering (as far as possible with wlroots)
```
Shouldn't it be changed to Aquamarine now? I didn't submit a PR because I am not exactly sure what handles cursor rendering now

**Comment by VirtCode** [comment]
sure, thanks for pointing it out
the "limitation" of mentioned was one that is general to how hw cursors work, not wlroots, so it wasn't correct anyways
