### ISSUE TITLE
Add setting to set maxium cursor will expand

### ISSUE THREAD

**Issue by nonetrix** [VirtCode/hypr-dynamic-cursors#18]
KDE has feature where cursor will expand infinitely, in my opinion this is a feature missing from Hyprland. For feature parity you should be able to set maximum size cursor will expand when it is shaken, or completely disable it (KDE mode)

This is very serious request and is not partly a joke at all, Hyprland needs feature parity. But in all seriousness this would be a nice feature, and I guess you can also replicate the funny KDE bug if you want but it's nice outside of that

**Comment by VirtCode** [comment]
Yeah, the current shake-to-zoom impl is a bit lackluster, and I can fully see the importance of cursors which fill the entire screen. 
I'll probably rewrite the shaking stuff some time in the future.

**Comment by VirtCode** [comment]
I've updated the shaking behavior such that it is more customizable and feels more satisfying and fluid. As a result, the cursor can now expand infinitely (and does so by default). 

Thanks for bringing this serious issue to my attention, it should finally be resolved now.
