### ISSUE TITLE
Pixelated Cursor Shake

### ISSUE THREAD

**Issue by CrossScarDev** [VirtCode/hypr-dynamic-cursors#20]
When I have the Enlarge Cursor on Shake option enabled the cursor is pixelated even when using hyprcursor.

**Comment by VirtCode** [comment]
yes, it currently only takes the current cursor texture and scales it up. It is already on the [to-do list](https://github.com/VirtCode/hypr-dynamic-cursors?tab=readme-ov-file#state) that we render a high-res image taken from hyprcursor (if possible) instead. But thanks for reporting, now I know someone even uses hyprcursor and wants to see this.

**Comment by littleblack111** [comment]
nice!

**Comment by VirtCode** [comment]
I've finally had some time to implement this. Should be available on the latest commit (which happens to be compatible with v0.45.0).

Be sure you are using a hyprcursor theme that is **based on SVGs**. See the [hyprcursor section](https://github.com/VirtCode/hypr-dynamic-cursors?tab=readme-ov-file#hyprcursor) in the readme for more information and the caveats that come with this.

**Comment by dp0sk** [comment]
thank you!

**Comment by dp0sk** [comment]
> I've finally had some time to implement this. Should be available on the latest commit (which happens to be compatible with v0.45.0).
> 
> Be sure you are using a hyprcursor theme that is **based on SVGs**. See the [hyprcursor section](https://github.com/VirtCode/hypr-dynamic-cursors?tab=readme-ov-file#hyprcursor) in the readme for more information and the caveats that come with this.

so i cant enable it. :hyprcursor thing works as well? but not svg cursors

**Comment by VirtCode** [comment]
You need to have a hyprcursor theme that is based on SVGs. Non-SVG hyprcursor themes might also work but look no better than before in most cases, and normal XCursor themes are not supported (it will just be pixelated).

To get an appropriate theme, head into the [#hyprcursor-themes](https://discord.com/channels/961691461554950145/1216066899729977435) channel on the hyprland discord and download one that advertises itself as SVG. Then see the [hyprcursor](https://discord.com/channels/961691461554950145/1216066899729977435) wiki page for where to extract it to and how to enable it.
