### ISSUE TITLE
Cursor does not render properly on scaled monitor

### ISSUE THREAD

**Issue by Eggrror404** [VirtCode/hypr-dynamic-cursors#21]
On the latest Hyprland version (v0.43.0),
enabling the plugin makes the cursor invisible in right and bottom parts of a scaled monitor

And the "invisible region" gets bigger for a larger scale, I suspect the plugin is not properly handling the monitor scale?

The shake-to-find enlarged cursor does sometimes render in the region though.

here's `hyprctl version` and the monitor having the issue
```
> hyprctl version
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196
```
```
monitor=DP-1,2560x1440@144.01,0x0,1.25
```

**Comment by VirtCode** [comment]
should be fixed with the latest commit, thanks for reporting!
