### ISSUE TITLE
dynamic-cursors shifts cursor position

### ISSUE THREAD

**Issue by littleblack111** [VirtCode/hypr-dynamic-cursors#22]
i have a hidpi display. dont know if thats related

**Comment by littleblack111** [comment]
seems like a hardware cursor issue. fixed with software cursor, but still worth looking into

**Comment by littleblack111** [comment]
nvm i read cursor:allow_dumb_copy = true is not supported

**Comment by VirtCode** [comment]
yeah, nvidia is only supported with software cursors for now, sorry about that

I'll try to implement hardware cursor support once hyprland properly supports them on nvidia. The current implementation / hack (dumb copy) is very basic and for example doesn't even accommodate for rotated displays. There are already some solutions in the works but they will probably take some more time.

**Comment by littleblack111** [comment]
alright, got it
