### ISSUE TITLE
suggestion - suck onto object

### ISSUE THREAD

**Issue by littleblack111** [VirtCode/hypr-dynamic-cursors#23]
like the ipad cursor, it can suck onto object. i find that really cool

if you have no idea what do i mean. here is an example: https://youtu.be/tGVQAQw-D9E?si=8-OG2iQf-4z_dCMi&t=147

you can see the cursor stayed at the element and adapted its texture?

**Comment by VirtCode** [comment]
This would indeed be very cool, but to my knowledge this is currently not possible on wayland. For that to work we'd have to know where buttons and other interaction elements were on the screen, so the apps would need to communicate this to the compositor. I don't think there's currently a protocol for that.

Maybe this will become possible in the future, through some hypothetical accessibility protocol or something similar, but for now I'd say this is pretty much impossible to achieve nicely. But thanks anyway for the suggestion.

**Comment by littleblack111** [comment]
got it!
