### ISSUE TITLE
shaperule does not apply to clientside cursor while the effects does

### ISSUE THREAD

**Issue by littleblack111** [VirtCode/hypr-dynamic-cursors#24]
i have mode = stretch and shaperule text none, apply to most stuff but not xwayland which have client side cursor

**Comment by VirtCode** [comment]
Yeah, the thing with client-side cursors is that the client (window) just gives the compositor a texture to show as the cursor. This means, the compositor doesn't know what shape the cursor currently is, and thus this plugin can't differentiate between them. So shape rules can't apply on a specific shape if it is client-side.

There is a special shape `clientside`, which applies if the cursor is client-side, so you can at least change things for all client-side cursors at once, if that is of some use to you.

**Comment by littleblack111** [comment]
danm alright then. seem like a downside of client-side cursor
