### ISSUE TITLE
cursor sometimes glitches...

### ISSUE THREAD

**Issue by littleblack111** [VirtCode/hypr-dynamic-cursors#25]
in the example video, i just right click the terminal, or get it into the text cursor then quit the terminal to change focus from the terminal. then it just glitches. but its definatly not limited to just alacritty, in browser etc ive noticed that too

https://fs.littleblack111.com/sdfgsadfg.mp4

**Comment by littleblack111** [comment]
yep. i have, for text: ```        shaperule = text, none
```

**Comment by VirtCode** [comment]
okay, I can reproduce it on my system, I'll have a look at it later today

**Comment by VirtCode** [comment]
sorry took a bit longer, should be fixed with this commit

**Comment by littleblack111** [comment]
no worries, ty! confirm fixed

**Comment by littleblack111** [comment]
@VirtCode ref https://github.com/hyprwm/aquamarine/pull/96
