### ISSUE TITLE
dynamic cursors could not be enabled

### ISSUE THREAD

**Issue by HarshNarayanJha** [VirtCode/hypr-dynamic-cursors#31]
Since after updating hyprland, (I don't remember if that's the case really), I am not able to start dynamic cursors.

If I run `hyprpm reload` or `hyprpm enable dynamic-cursors`, I get this notification...

`Failed to load, hooks could not be made`

![image](https://github.com/user-attachments/assets/025de79a-d9ac-46c0-8a02-96ef5a01afe6)

I have tried running `hyprpm update`

Hyprland version:
```fish
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.3
```

**Comment by VirtCode** [comment]
Can you have a look at the hyprland logs and share the part when the plugin is loaded? It should contain more information about what exactly is failing.

Also, what distro are you on?

**Comment by HarshNarayanJha** [comment]
Did a weekly restart, and it started working again, how could I miss that point... 🤦🏼 
Sorry couldn't get the logs

Also, I am on garuda linux (arch based)
