### ISSUE TITLE
Proposal: Add a category of audio effects

### ISSUE THREAD

**Issue by 0x000C0A71** [VirtCode/hypr-dynamic-cursors#35]
For example:
- Cursor shakes to the beat of the playing media

**Comment by VirtCode** [comment]
Hmm, I thought about this one for a bit, but I think this is out of scope for the moment.

Receiving and processing sound sounds (no pun intended) painful and would require additional dependencies outside of hyprland, i.e. some lib to interact with the sound system(s) and something for the fft. I'd rather avoid having dependencies other than hl for now.
