### ISSUE TITLE
dynamic-cursors failed to load

### ISSUE THREAD

**Issue by BeshoyEhab** [VirtCode/hypr-dynamic-cursors#36]
I have installed the plugin with hyprpm without any error but when I run 
`hyprpm load`
 it gives me this notification
`[dynamic-cursors] failed to load, hooks could not be made!`
and I don't know what to do.
Any help?

**Comment by VirtCode** [comment]
Can you try [getting the log](https://wiki.hyprland.org/Crashes-and-Bugs/#getting-the-log) for when you load the plugin? There should be more information in there about what's going on.

Also, what hyprland version and distro are you using?

**Comment by BeshoyEhab** [comment]
sorry the problem solve when I reinstall hyprland-git
