### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dp0sk** [VirtCode/hypr-dynamic-cursors#38]
hyprpm add https://github.com/VirtCode/hypr-dynamic-cursors/ --verbose
[v] version returned: Hyprland 0.45.0 built from branch  at commit a425fbebe4cf4238e48a42f724ef2208959d66cf  (version: bump to 0.45.0).
Date: Sat Nov 9 14:27:47 2024
Tag: v0.45.0, commits: 5433
built against aquamarine 0.4.4

flags set:
debug

[v] parsed commit a425fbebe4cf4238e48a42f724ef2208959d66cf at branch  on Sat Nov 9 14:27:47 2024, commits 5433
✔ adding a new plugin repository from https://github.com/VirtCode/hypr-dynamic-cursors/
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

→ Cloning https://github.com/VirtCode/hypr-dynamic-cursors/                                                                                                                                                 
✔ cloned                                                                                                                                                                                                    
✔ found hyprpm manifest                                                                                                                                                                                     
✔ parsed manifest, found 1 plugins:                                                                                                                                                                         
→ dynamic-cursors by Virt version                                                                                                                                                                           
→ Manifest has 5 pins, checking                                                                                                                                                                             
✔ Hyprland headers OK                                                                                                                                                                                       
→ Building dynamic-cursors                                                                                                                                                                                  
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)terminate called after throwing an instance of 'std::format_error'                                                            
  what():  format error: invalid arg-id in format string
fish: Job 1, 'hyprpm add https://github.com/V…' terminated by signal SIGABRT (Abort)

**Comment by VirtCode** [comment]
oh yeah right, never actually tested the build with hyprpm

should be fixed with the coming commit
