### ISSUE TITLE
Invisible on latest hyprland

### ISSUE THREAD

**Issue by nnra6864** [VirtCode/hypr-dynamic-cursors#48]
Not sure what happened, I am using software cursors since hw cursors cause insta crash on nvidia w this plugin for me.

**Comment by VirtCode** [comment]
yup, software cursors are currently broken because of hyprland's renderer rewrite. Will try to update the plugin in a couple of days, am quite busy atm

**Comment by VirtCode** [comment]
should be fixed

**Comment by nnra6864** [comment]
> should be fixed

Can confirm.

**Comment by nnra6864** [comment]
Hey, don't wanna be opening a new issue but it seems to be broken again(unless I messed something up).
It just straight up doesn't do anything rn.

**Comment by VirtCode** [comment]
what version are you on? just fixed the build for `-git` in 55fd61757b952c65d3226d3c834cdee5b394429f. 

Also note that since you're on nvidia, you now need to force software cursors manually, as hl has changed the default recently

**Comment by nnra6864** [comment]
Hey, I just updated and can confirm that it works.
Also, I always had software cursors faced cuz nvidia:
`cursor:no_hardware_cursors = 2 # Improves performance significantly for me, especially with dynamic-cursors`
Thanks for the quick fix!
