### ISSUE TITLE
grow around hotspot

### ISSUE THREAD

**Issue by Jappie3** [VirtCode/hypr-dynamic-cursors#5]
This is very much a nitpick, but is it possible to, when shaking the cursor, make it grow around the hotspot? The way it is currently implemented works for the default right-handed pointer cursor (since it has the hotspot in the top left), but the crosshair shape used in gimp or the text shape get larger in the bottom-right direction, offsetting the hotspot (again, very much a nitpick).

Example: the pixel in the top left is the actual position of my cursor, while the crosshair grew to the bottom right

![image](https://github.com/VirtCode/hypr-dynamic-cursors/assets/42720120/5bc9de7d-0b8f-4cb1-a8cf-63ae0d238426)

**Comment by VirtCode** [comment]
did you try the latest commit? thought I'd fixed that yesterday (https://github.com/VirtCode/hypr-dynamic-cursors/commit/80750df211d2188033a410af07f12e7f48549d96)

**Comment by Jappie3** [comment]
that fixes the problem, seems I was too hasty - thanks :)
