### ISSUE TITLE
Cursor image isn't always updated

### ISSUE THREAD

**Issue by vaxerski** [VirtCode/hypr-dynamic-cursors#8]
Yo yo yo.

Sometimes, the cursor image is not updated due to yer plugin. Some apps that exhibit this:
 - BlueMail (xwayland, electron)
 - Tutanota (xwayland, electron)
 - Photoshop (xwayland, wine)
 
Haven't noticed any other, yet.

The cursor image is stuck on the first one the app sets.

**Comment by VirtCode** [comment]
Now that you mention it, I think I've also seen this bug in some xwayland apps (but thought it was some xwayland issue). Thanks for the report, I'll dig into it tomorrow.

**Comment by VirtCode** [comment]
Turns out I removed some logic while testing some time ago, which stopped the wl surface from updating. Should be fixed now.

**Comment by vaxerski** [comment]
thanks!
